image: gcrkrause/loopp-docker-build-env

build:
  script: 
    - meson --prefix /usr build
    - ninja -C build
    - DESTDIR=./appdir ninja -C build install ; find ./build/appdir
    - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    - /linuxdeployqt-continuous-x86_64.AppImage --appimage-extract
    - squashfs-root/AppRun build/appdir/usr/share/applications/*.desktop -appimage

  artifacts:
    untracked: false
    expire_in: 30 days
    paths: 
      - Luppp-*.AppImage*
      - build/meson-logs